services:
  - type: web
    name: cliente-admin-django
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn cliente_admin_django.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cliente_admin_django.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
    autoDeploy: true
    plan: free